name: ci-app

on: push
jobs:
  run: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: make setup
      - run: make start
      - run: make lint
      - run: make test
